# https://zero-to-jupyterhub.readthedocs.io/en/latest/setup-jupyterhub.html#
proxy:
  secretToken: "39a5793cbb4fac2586a6625e03bbe1ccc7d277e300dbad45ce47656eaa500b8b"
singleuser:
  # https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html
  image:
    name: pupster90/io
    tag: try6
  # https://zero-to-jupyterhub.readthedocs.io/en/latest/user-environment.html
  lifecycleHooks:
    postStart:
      exec:
        command: ["sh","-c","rm -rf welcome_to_io && git clone https://github.com/pupster90/welcome_to_io.git"]
        #command: ["sh","-c","git clone https://github.com/pupster90/welcome_to_io.git && rm -rf welcome_to_io/.git  && mv welcome_to_io/* ./ && rm -rf welcome_to_io"]
  # https://zero-to-jupyterhub.readthedocs.io/en/latest/user-storage.html
  storage:
    dynamic:
      storageClass: jupyterhub-user-ssd
# https://zero-to-jupyterhub.readthedocs.io/en/latest/optimization.html
prePuller:
  hook:
    enabled: false
  continuous:
    enabled: true
# https://zero-to-jupyterhub.readthedocs.io/en/latest/authentication.html
#auth:
#  type: google
#  google:
#    clientId: "244479093220-89vej4bcpg18nf5b0ouk7q5vs7bks5r4.apps.googleusercontent.com"
#    clientSecret: "qnKEczw2QzQvuavznaIqITmI"
#    callbackUrl: "http://idekerlab.io.computer/hub/oauth_callback"
#    hostedDomain: "ucsd.edu"
#    loginService: "UCSD"
